name: "Build Devcontainer"
on: { push: { paths: [".devcontainer/Dockerfile"] }, workflow_dispatch: {} }

jobs:
  build:
    name: "Build Container"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Build Images"
        run: |
          cd .devcontainer
          docker build -t ghcr.io/${{ github.repository_owner }}/devcontainer-discord:codespace --build-arg IMAGE=mcr.microsoft.com/vscode/devcontainers/base:bullseye .
          docker build -t ghcr.io/${{ github.repository_owner }}/devcontainer-discord:vscserver --build-arg IMAGE=gitpod/openvscode-server:latest,USER=openvscode-server .

      - name: "Cache Layers"
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: "Push Images"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/devcontainer-discord:codespace
          docker push ghcr.io/${{ github.repository_owner }}/devcontainer-discord:vscserver
